#!/bin/sh
#echo “Enter the LogGroupName”
#read LogGroupName
#echo “Enter the FilterName”
#read FilterName
#echo “Enter the MetricName”
#read MetricName
#echo “Enter the MetricNamespace”
#read MetricNamespace
#echo “Enter the AlarmName”
#read AlarmName
source /root/newremedies/variables.sh
echo "Creating Metric and Alarm"
TopicArn=$(aws sns list-topics | grep TopicArn | gawk -F' ' {'print $2'} | sed 's/"//g' | sed 's/,//g')
if [ "$( aws logs put-metric-filter --log-group-name $LogGroupName --filter-name $FilterName6 --metric-transformations metricName=$MetricName6,metricNamespace=$MetricNamespace6,metricValue=1 --filter-pattern '{($.eventName = ConsoleLogin) && ($.errorMessage = "Failed authentication") }')" ];then
     echo "Metric Created"
fi  
echo "Creating Alarm"
 if [ "$(aws cloudwatch put-metric-alarm --alarm-name $AlarmName6 --metric-name $MetricName6 --statistic Sum --period 300 --threshold 1 --comparison-operator GreaterThanOrEqualToThreshold --evaluation-periods 1 --namespace $MetricNamespace6 --alarm-actions $TopicArn )" ];then
       echo "FAILED"
        else
       echo "3.6 PASSED"
    fi
