#!/bin/bash
for Arn in ` aws iam list-policies  | jq '.Policies[].Arn' | grep AWSSupportAccess | sed 's/"//g'`;
do
if [ "$(aws iam list-entities-for-policy --policy-arn  $Arn)" ]; then
    echo "1.20  PASSED"
else
    echo "Creating Role"
	aws iam create-role --role-name $Rolename --assume-role-policy-document file://Trustpolicy.json
	echo "Role Created"
	aws iam attach-role-policy --policy-arn arn:aws:iam::aws:policy/AWSSupportAccess --role-name $Rolename
fi
done
