#!/bin/sh
#echo “Enter the LogGroupName”
#read LogGroupName
#echo “Enter the FilterName”
#read FilterName
#echo “Enter the MetricName”
#read MetricName
#echo “Enter the MetricNamespace”
#read MetricNamespace
#echo “Enter the AlarmName”
#read AlarmName
source /root/newremedies/variables.sh
echo "Creating Metric and Alarm"
TopicArn=$(aws sns list-topics | grep TopicArn | gawk -F' ' {'print $2'} | sed 's/"//g' | sed 's/,//g')
if [ "$( aws logs put-metric-filter --log-group-name $LogGroupName --filter-name $FilterName2 --metric-transformations metricName=$MetricName2,metricNamespace=$MetricNamespace2,metricValue=1 --filter-pattern '{($.eventName = "ConsoleLogin") && ($.additionalEventData.MFAUsed != "No")}')" ];then
fi  
echo "Creating Alarm"
 if [ "$(aws cloudwatch put-metric-alarm --alarm-name $AlarmName2 --metric-name $MetricName2 --statistic Sum --period 300 --threshold 1 --comparison-operator GreaterThanOrEqualToThreshold --evaluation-periods 1 --namespace $MetricNamespace2 --alarm-actions $TopicArn )" ];then
       echo "FAILED"
        else
       echo "3.2 PASSED"
    fi
